package sanjarbek.uz.vakanuz.domain.moc_data

import sanjarbek.uz.vakanuz.domain.models.announcement.AnnouncementModel

object AppHardCodeData {
    val announcementList = listOf(
        AnnouncementModel(
            id = 1,
            category = "Developer",
            date = 1750273200000,
            organization = "Aloqa Bank",
            region = "Toshkent, Yunusobod",
            jobName = "Android and Flutter developer",
            purposeWork = "Bank mobil ilovalarini ishlab chiqish, ularni yangilab borish, foydalanuvchi tajribasini yaxshilash, hamda xavfsizlikni ta'minlash. Loyihalarda faol ishtirok etish va yangi funksiyalarni integratsiya qilish.",
            requirements = "Kotlin dasturlash tilini chuqur bilish, Android SDK bilan ishlash tajribasi, REST API’lar bilan integratsiya qilish, Git va Clean Architecture prinsiplarini tushunish.",
            weOffer = "Yuqori darajadagi texnik jamoa, zamonaviy ofis, kafolatlangan bonus tizimi, yillik professional rivojlanish uchun budjet, va bepul tushlik.",
            technology = "Kotlin, Firebase (Auth, Firestore, Storage), Retrofit, Coroutines, Jetpack Compose, Git, MVVM, CI/CD",
            languages = "Ingliz tili - B2, Rus tili - A1, O'zbek tili - C1",
            additionalInformation = "Minimal 1 yil ishlab chiqarish tajribasi, portfolioda kamida 1 ta real loyiha bo‘lishi kerak. Ilovani Play Market’da ko‘rish mumkin bo‘lishi maqsadga muvofiq.",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "8 soat",
            workFormat = "Offline",
            minPrice = "8 000 000",
            maxPrice = "12 000 000",
            phoneNumber = "+998944856603",
        ),
        AnnouncementModel(
            id = 2,
            category = "Developer",
            date = 1750273200000,
            organization = "IT Park",
            region = "Toshkent, Chilonzor",
            jobName = "Frontend developer",
            purposeWork = "Yangi loyihalarning foydalanuvchi interfeyslarini yaratish, mavjud tizimlarni optimallashtirish, mobil va desktop platformalarda bir xilda ishlashini ta’minlash. Dizayndan kodgacha barcha bosqichlarda qatnashish.",
            requirements = "JavaScript, React.js, TypeScript, HTML5, CSS3 bo‘yicha chuqur bilim. Responsive dizaynlar bilan ishlash, Git orqali versiyalarni boshqarish, REST API bilan ishlash tajribasi, cross-browser muvofiqligi.",
            weOffer = "Masofadan ishlash imkoniyati, erkin grafik, zamonaviy texnologiyalar bilan ishlash, jamoaviy meetup va hackathonlarda qatnashish imkoniyati, cheksiz qahva va chill zona.",
            technology = "React, TypeScript, Redux Toolkit, SCSS, TailwindCSS, GitHub Actions, Figma, Jest, Cypress",
            languages = "Ingliz tili - B1, Rus tili - B2",
            additionalInformation = "Dasturlash bo‘yicha onlayn portfoliongiz (GitHub, Codepen, yoki boshqa) bo‘lishi zarur. 2 yil frontendda ishlagan afzal. Dizayn va foydalanuvchi tajribasiga qiziqish bo‘lishi maqsadga muvofiq.",
            experience = "1-3-yil",
            employment = "Yarim stavka",
            graph = "4/2",
            workingTime = "6 soat",
            workFormat = "Remote",
            minPrice = "6 000 000",
            maxPrice = "9 000 000",
            phoneNumber = "+998935551234",
        ),
        AnnouncementModel(
            id = 3,
            category = "Developer",
            date = 1750273200000,
            organization = "Digital One",
            region = "Samarqand",
            jobName = "Backend Developer",
            purposeWork = "Web ilovalarning server qismini ishlab chiqish, REST API’lar yaratish, ma’lumotlar bazasini loyihalash va optimallashtirish, xavfsizlikni ta’minlash va mikroservislar bilan ishlash.",
            requirements = "Node.js, Express.js, PostgreSQL, JWT, RESTful API, Git, Docker, Redis bo‘yicha chuqur bilim. Unit test va integration test yozish tajribasi. Tizimlarni modul tarzida tuza olish.",
            weOffer = "Qulay ofis, bepul tushlik, shaxsiy rivojlanish uchun kurslar, jamoaviy treninglar va yaxshi kayfiyatdagi jamoa.",
            technology = "Node.js, PostgreSQL, Sequelize ORM, Redis, Docker, Git, Swagger, GitLab CI/CD",
            languages = "Rus tili - B2",
            additionalInformation = "CRM, ERP tizimlar bilan ishlagan bo‘lsangiz afzal. Kod sifati muhim. Arxitektura haqida tushunchaga ega bo‘lishingiz kerak.",
            experience = "2-5-yil",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "8 soat",
            workFormat = "Gibrid",
            minPrice = "10 000 000",
            maxPrice = "14 000 000",
            phoneNumber = "+998901112233"
        ),
        AnnouncementModel(
            id = 4,
            category = "Developer",
            date = 1750273200000,
            organization = "UzCard",
            region = "Toshkent, Olmazor",
            jobName = "DevOps Engineer",
            purposeWork = "CI/CD jarayonlarini yaratish va avtomatlashtirish, tizimlarning uzluksiz ishlashini ta’minlash, monitoring qilish va server infratuzilmasini boshqarish.",
            requirements = "Linux, Docker, Jenkins, Kubernetes, Git, AWS bilan tajriba. Infrastructure as Code (Terraform, Ansible) haqida bilim. Monitoring vositalari bilan ishlash.",
            weOffer = "Professional jamoa, yuqori maosh, o‘zlashtirish uchun kurslar, tibbiy sug‘urta, sport zali kartasi, zamonaviy texnik baza.",
            technology = "Docker, Jenkins, Kubernetes, AWS, Prometheus, Grafana, GitLab, Terraform, Ansible",
            languages = "Ingliz tili - C1, O'zbek tili - C2",
            additionalInformation = "Senior daraja talab qilinadi. Yiliga kamida 2 marta sertifikat yangilanishi uchun ko‘mak beriladi. SRE tajribasi bo‘lsa, afzal.",
            experience = "3-5-yil",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "9 soat",
            workFormat = "Offline",
            minPrice = "12 000 000",
            maxPrice = "18 000 000",
            phoneNumber = "+998933456789"
        ),
        AnnouncementModel(
            id = 5,
            category = "Developer",
            date = 1750273200000,
            organization = "MyTaxi",
            region = "Toshkent, Yakkasaroy",
            jobName = "iOS Developer",
            purposeWork = "iOS ilovalarni noldan ishlab chiqish va mavjudlarini yangilash, foydalanuvchi interfeysini silliq va tez ishlovchi holga keltirish.",
            requirements = "Swift, UIKit, MVVM arxitekturasi, REST API bilan ishlash, Git bilan versiya nazorati, Firebase integratsiyasi.",
            weOffer = "Yillik bonuslar, tajribali ustozdan mentoring, Apple texnikalar bilan ta’minlash, sertifikatlash kurslari uchun qo‘llab-quvvatlash.",
            technology = "Swift, Xcode, UIKit, SwiftUI, Firebase, Git, Fastlane, Alamofire",
            languages = "Ingliz - B2",
            additionalInformation = "Portfolio bo‘lishi majburiy. App Store’da chop etilgan kamida 1 ta loyiha talab qilinadi.",
            experience = "1-3-yil",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "8 soat",
            workFormat = "Hybrid",
            minPrice = "9 000 000",
            maxPrice = "13 000 000",
            phoneNumber = "+998938888888"
        ),
        AnnouncementModel(
            id = 6,
            category = "Developer",
            date = 1750273200000,
            organization = "BePro",
            region = "Farg'ona",
            jobName = "QA Engineer",
            purposeWork = "Mobil va web ilovalarni sinash, xatoliklarni aniqlash va hujjatlashtirish, avtomatlashtirilgan test skriptlarini yozish va test natijalarini tahlil qilish.",
            requirements = "Manual test metodologiyasi, Selenium WebDriver, TestNG, Postman, JIRA, test yozuvlari, bug reportlar bilan ishlash. SDLC haqida tushuncha.",
            weOffer = "Mentorlik dasturi, professional treninglar, onlayn kurslar uchun budjet, masofadan ishlash imkoniyati va yaxshi jamoa muhiti.",
            technology = "Selenium, JIRA, TestRail, Postman, Jenkins, Git, Appium, REST Assured",
            languages = "Ingliz - B1",
            additionalInformation = "O‘rta darajadagi test tajribasi talab qilinadi. Test yozish misollarini intervyu jarayonida keltirish so‘raladi.",
            experience = "1-3-yil",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "8 soat",
            workFormat = "Remote",
            minPrice = "7 000 000",
            maxPrice = "10 000 000",
            phoneNumber = "+998939393939"
        ),
        AnnouncementModel(
            id = 7,
            category = "Developer",
            date = 1750273200000,
            organization = "Diyor Tech",
            region = "Andijon",
            jobName = "Fullstack Developer",
            purposeWork = "Frontend va backend qismlarini birgalikda ishlab chiqish, API yaratish, foydalanuvchi interfeysi va server o‘rtasida muvofiqlikni ta’minlash.",
            requirements = "React.js, Node.js, MongoDB, REST API, JWT, Git, Redux bo‘yicha bilim. OOP va tizimli fikrlash.",
            weOffer = "Yosh va dinamik jamoa, tajriba orttirish imkoniyati, shaxsiy loyihalarda qatnashish, remote rejimda ishlash imkoniyati.",
            technology = "React.js, Node.js, Express, MongoDB, TailwindCSS, Git, Postman",
            languages = "Rus - B1",
            additionalInformation = "Yangi boshlovchilar ham murojaat qilishlari mumkin. Portfolioda kamida 1 loyiha ko‘rsatilishi zarur.",
            experience = "0-1-yil",
            employment = "Yarim stavka",
            graph = "4/3",
            workingTime = "6 soat",
            workFormat = "Remote",
            minPrice = "5 000 000",
            maxPrice = "8 000 000",
            phoneNumber = "+998931111111"
        ),
        AnnouncementModel(
            id = 8,
            category = "Developer",
            date = 1750273200000,
            organization = "Sky Soft",
            region = "Navoiy",
            jobName = "Project Manager",
            purposeWork = "Loyihani boshidan oxirigacha rejalashtirish, resurslarni boshqarish, jamoa bilan ishlash, deadline’larni nazorat qilish va mijozlar bilan aloqada bo‘lish.",
            requirements = "Agile, Scrum, JIRA, Trello bilan ishlash tajribasi, jamoaviy boshqaruv ko‘nikmalari, vaqtni boshqarish va muammo hal qilish qobiliyati.",
            weOffer = "Karyera o‘sish imkoniyati, yaxshi jamoa, xodimlar uchun soft skills treninglari, ofis ichida sport va dam olish zonasi.",
            technology = "JIRA, Trello, Confluence, Slack, Google Workspace, Microsoft Project",
            languages = "Ingliz - B2",
            additionalInformation = "PMP sertifikati bo‘lsa afzal. Kamida 3 yillik boshqaruv tajribasi talab qilinadi.",
            experience = "3-5-yil",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "9 soat",
            workFormat = "Offline",
            minPrice = "15 000 000",
            maxPrice = "20 000 000",
            phoneNumber = "+998907777777"
        ),
        AnnouncementModel(
            id = 9,
            category = "Developer",
            date = 1750273200000,
            organization = "CodeX",
            region = "Toshkent, Mirzo Ulug‘bek",
            jobName = "UI/UX Designer",
            purposeWork = "Foydalanuvchi interfeyslarini loyihalash, foydalanuvchi tajribasini tahlil qilish, mockup va prototiplar tayyorlash, dizaynning implementatsiyasini kuzatish.",
            requirements = "Figma, Adobe XD, Sketch, Design System yaratish, UX research metodlari, WCAG accessibility bilimlari.",
            weOffer = "Ijodiy muhit, dizayn hackathonlar, doimiy portfolioni to‘ldirish imkoniyati, bepul treninglar.",
            technology = "Figma, Adobe XD, InVision, Zeplin, Miro, Notion",
            languages = "Ingliz - B1",
            additionalInformation = "Portfolio ko‘rsatilishi shart. Intervyuda dizayn yechimlaringizni izohlab bera olish muhim.",
            experience = "1-2-yil",
            employment = "To'liq bandlik",
            graph = "5/2",
            workingTime = "8 soat",
            workFormat = "Hybrid",
            minPrice = "8 000 000",
            maxPrice = "10 000 000",
            phoneNumber = "+998937777777"
        ),
        AnnouncementModel(
            id = 10,
            category = "Developer",
            date = 1750273200000,
            organization = "NextGen Soft",
            region = "Buxoro",
            jobName = "System Administrator",
            purposeWork = "Tashkilot ichidagi server va tarmoqlarni sozlash, kuzatish va nosozliklarni bartaraf qilish. Har kuni tizimni xavfsiz ishlashini ta'minlash.",
            requirements = "Linux va Windows server, Active Directory, DNS, DHCP, Bash scripting, Zabbix monitoring bo‘yicha bilimlar. Problemani tez hal qilish.",
            weOffer = "Treninglar, ichki IT bo‘yicha sertifikatlar, texnik tajribaga ega ustozlar, yaxshi ish muhiti va bonuslar.",
            technology = "Linux (Ubuntu, CentOS), Windows Server, Zabbix, Bash, PowerShell, VMware, Cisco",
            languages = "Rus - B2",
            additionalInformation = "Shoshilinch lavozim. Tez ish boshlashga tayyor xodimlar afzal. Qabul sinovli intervyu asosida amalga oshiriladi.",
            experience = "1-3-yil",
            employment = "To'liq bandlik",
            graph = "6/1",
            workingTime = "8 soat",
            workFormat = "Offline",
            minPrice = "9 000 000",
            maxPrice = "11 000 000",
            phoneNumber = "+998907654321"
        )
    )
}